//
//
#ifndef VOLCANO_UI_SOUND_COMMON_HPP
#define VOLCANO_UI_SOUND_COMMON_HPP

#include <Volcano/UI/Common.hpp>

#define VOLCANO_UI_SOUND_BEGIN VOLCANO_UI_BEGIN namespace Sound {
#define VOLCANO_UI_SOUND_END } VOLCANO_UI_END

#endif // VOLCANO_UI_SOUND_COMMON_HPP
