//
//
#ifndef VOLCANO_CLIENT_SOUND_COMMON_HPP
#define VOLCANO_CLIENT_SOUND_COMMON_HPP

#include <Volcano/Client/Common.hpp>

#define VOLCANO_CLIENT_SOUND_BEGIN VOLCANO_CLIENT_BEGIN namespace Sound {
#define VOLCANO_CLIENT_SOUND_END } VOLCANO_CLIENT_END

#endif // VOLCANO_CLIENT_SOUND_COMMON_HPP
