//
//
#ifndef VOLCANO_GAME_TEMPLATES_FPS_COMMON_HPP
#define VOLCANO_GAME_TEMPLATES_FPS_COMMON_HPP

#include <Volcano/Game/Templates/Common.hpp>

#define VOLCANO_GAME_TEMPLATES_FPS_BEGIN VOLCANO_GAME_TEMPLATES_BEGIN namespace FPS {
#define VOLCANO_GAME_TEMPLATES_FPS_END } VOLCANO_GAME_TEMPLATES_END

#endif // VOLCANO_GAME_TEMPLATES_FPS_COMMON_HPP
