//
//
#ifndef VOLCANO_GRAPHICS_VULKAN_COMMON_HPP
#define VOLCANO_GRAPHICS_VULKAN_COMMON_HPP

#include <Volcano/Graphics/Common.hpp>

#define VOLCANO_GRAPHICS_VULKAN_BEGIN VOLCANO_GRAPHICS_BEGIN namespace Vulkan {
#define VOLCANO_GRAPHICS_VULKAN_END } VOLCANO_GRAPHICS_END

#endif // VOLCANO_GRAPHICS_VULKAN_COMMON_HPP
