//
//
#ifndef VOLCANO_SOUND_OPENAL_COMMON_HPP
#define VOLCANO_SOUND_OPENAL_COMMON_HPP

#include <Volcano/Sound/Common.hpp>

#define VOLCANO_SOUND_OPENAL_BEGIN VOLCANO_SOUND_BEGIN namespace OpenAL {
#define VOLCANO_SOUND_OPENAL_END } VOLCANO_SOUND_END

#endif // VOLCANO_SOUND_OPENAL_COMMON_HPP
