//
//
#ifndef VOLCANO_EDITOR_DEBUGDRAWRENDERER_HPP
#define VOLCANO_EDITOR_DEBUGDRAWRENDERER_HPP

#include <debug_draw.hpp>

#include <Volcano/Editor/Common.hpp>

VOLCANO_EDITOR_BEGIN



VOLCANO_EDITOR_END

#endif // VOLCANO_EDITOR_DEBUGDRAWRENDERER_HPP
