//
//
#ifndef VOLCANO_GRAPHICS_OPENGL_COMMON_HPP
#define VOLCANO_GRAPHICS_OPENGL_COMMON_HPP

#include <Volcano/Graphics/Common.hpp>

#define VOLCANO_GRAPHICS_OPENGL_BEGIN VOLCANO_GRAPHICS_BEGIN namespace OpenGL {
#define VOLCANO_GRAPHICS_OPENGL_END } VOLCANO_GRAPHICS_END

#endif // VOLCANO_GRAPHICS_OPENGL_COMMON_HPP
