//
//
#ifndef VOLCANO_ACOUSTICS_COMMON_HPP
#define VOLCANO_ACOUSTICS_COMMON_HPP

#include <Volcano/Common.hpp>

#define VOLCANO_ACOUSTICS_BEGIN VOLCANO_BEGIN namespace Acoustics {
#define VOLCANO_ACOUSTICS_END } VOLCANO_END

#endif // VOLCANO_ACOUSTICS_COMMON_HPP
