//
//
#ifndef VOLCANO_GAME_REGISTERTYPES_HPP
#define VOLCANO_GAME_REGISTERTYPES_HPP

#include <Volcano/Game/Common.hpp>

VOLCANO_GAME_BEGIN

void registerTypes(void);

VOLCANO_GAME_END

#endif // VOLCANO_GAME_REGISTERTYPES_HPP
