//
//
#ifndef VOLCANO_DRIVERS_SOUND_COMMON_HPP
#define VOLCANO_DRIVERS_SOUND_COMMON_HPP

#include <Volcano/Drivers/Common.hpp>

#define VOLCANO_DRIVERS_SOUND_BEGIN VOLCANO_DRIVERS_BEGIN namespace Sound {
#define VOLCANO_DRIVERS_SOUND_END } VOLCANO_DRIVERS_END

#endif // VOLCANO_DRIVERS_SOUND_COMMON_HPP
