//
//
#ifndef VOLCANO_VULKANRENDERER_COMMON_H
#define VOLCANO_VULKANRENDERER_COMMON_H

#include <Volcano/Common.h>

#if defined(VOLCANO_VULKANRENDERER)
#   define VOLCANO_VULKANRENDERER_API Q_DECL_EXPORT
#else
#   define VOLCANO_VULKANRENDERER_API Q_DECL_IMPORT
#endif

#define VOLCANO_VULKANRENDERER_BEGIN VOLCANO_BEGIN namespace OpenGLRenderer {
#define VOLCANO_VULKANRENDERER_END } VOLCANO_END

#endif // VOLCANO_VULKANRENDERER_COMMON_H
