//
//
#ifndef VOLCANO_GAME_CLIENT_COMMON_HPP
#define VOLCANO_GAME_CLIENT_COMMON_HPP

#include <Volcano/Game/Common.hpp>

#define VOLCANO_GAME_CLIENT_BEGIN VOLCANO_GAME_BEGIN namespace Client {
#define VOLCANO_GAME_CLIENT_END } VOLCANO_GAME_END

#endif // VOLCANO_GAME_CLIENT_COMMON_HPP
