//
//
#ifndef VOLCANO_GAME_TEMPLATES_COMMON_HPP
#define VOLCANO_GAME_TEMPLATES_COMMON_HPP

#include <Volcano/Game/Common.hpp>

#define VOLCANO_GAME_TEMPLATES_BEGIN VOLCANO_GAME_BEGIN namespace Templates {
#define VOLCANO_GAME_TEMPLATES_END } VOLCANO_GAME_END

#endif // VOLCANO_GAME_TEMPLATES_COMMON_HPP
