//
//
#ifndef VOLCANO_GAME_GRAPHICS_COMMON_HPP
#define VOLCANO_GAME_GRAPHICS_COMMON_HPP

#include <Volcano/Game/Common.hpp>

#define VOLCANO_GAME_GRAPHICS_BEGIN VOLCANO_GAME_BEGIN namespace Graphics {
#define VOLCANO_GAME_GRAPHICS_END } VOLCANO_GAME_END

#endif // VOLCANO_GAME_GRAPHICS_COMMON_HPP
