
function(volcano_enable_if COND)
	if(COND)
		return(${ARGN})
	else()
		return()
	endif()
endfunction()

function(volcano_option OPT DESC COND)
	if(${COND})
		set(VAL ON)
	else()
		set(VAL OFF)
	endif()
	message(STATUS "Option: ${OPT}\t= ${VAL}")
	set(${OPT} ${VAL} CACHE BOOL ${DESC})
endfunction()

macro(volcano_set_target_folder TARGET)
    file(RELATIVE_PATH RDIR ${CMAKE_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
    if(RDIR)
        set_target_properties(${TARGET} PROPERTIES FOLDER ${RDIR})
    endif()
endmacro()

macro(volcano_source_tree)
    source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${ARGN})
endmacro()

