//
//
#ifndef VOLCANO_GAME_SERVER_COMMON_HPP
#define VOLCANO_GAME_SERVER_COMMON_HPP

#include <Volcano/Game/Common.hpp>

#define VOLCANO_GAME_SERVER_BEGIN VOLCANO_GAME_BEGIN namespace Server {
#define VOLCANO_GAME_SERVER_END } VOLCANO_GAME_END

#endif // VOLCANO_GAME_SERVER_COMMON_HPP
