//
//
#ifndef VOLCANO_INPUT_DEFAULT_COMMON_HPP
#define VOLCANO_INPUT_DEFAULT_COMMON_HPP

#include <Volcano/Input/Common.hpp>

#define VOLCANO_INPUT_DEFAULT_BEGIN VOLCANO_INPUT_BEGIN namespace Default {
#define VOLCANO_INPUT_DEFAULT_END } VOLCANO_INPUT_END

#endif // VOLCANO_INPUT_DEFAULT_COMMON_HPP
