//
//
#ifndef VOLCANO_OPENGLRENDERER_COMMON_H
#define VOLCANO_OPENGLRENDERER_COMMON_H

#include <Volcano/Common.h>

#if defined(VOLCANO_OPENGLRENDERER)
#   define VOLCANO_OPENGLRENDERER_API Q_DECL_EXPORT
#else
#   define VOLCANO_OPENGLRENDERER_API Q_DECL_IMPORT
#endif

#define VOLCANO_OPENGLRENDERER_BEGIN VOLCANO_BEGIN namespace OpenGLRenderer {
#define VOLCANO_OPENGLRENDERER_END } VOLCANO_END

#endif // VOLCANO_OPENGLRENDERER_COMMON_H
