//
//
#ifndef VOLCANO_SERVER_COMMON_HPP
#define VOLCANO_SERVER_COMMON_HPP

#include <Volcano/Common.hpp>

#define VOLCANO_SERVER_BEGIN VOLCANO_BEGIN namespace Server {
#define VOLCANO_SERVER_END } VOLCANO_END

#endif // VOLCANO_SERVER_COMMON_HPP
