//
//
#ifndef VOLCANO_GAME_SOUND_COMMON_HPP
#define VOLCANO_GAME_SOUND_COMMON_HPP

#include <Volcano/Game/Common.hpp>

#define VOLCANO_GAME_SOUND_BEGIN VOLCANO_GAME_BEGIN namespace Sound {
#define VOLCANO_GAME_SOUND_END } VOLCANO_GAME_END

#endif // VOLCANO_GAME_SOUND_COMMON_HPP
