//
//
#ifndef VOLCANO_ACOUSTICS_OPENAL_COMMON_HPP
#define VOLCANO_ACOUSTICS_OPENAL_COMMON_HPP

#include <Volcano/Acoustics/Common.hpp>

#define VOLCANO_ACOUSTICS_OPENAL_BEGIN VOLCANO_ACOUSTICS_BEGIN namespace OpenAL {
#define VOLCANO_ACOUSTICS_OPENAL_END } VOLCANO_ACOUSTICS_END

#endif // VOLCANO_ACOUSTICS_OPENAL_COMMON_HPP
