//
//
#ifndef VOLCANO_COMMON_HPP
#define VOLCANO_COMMON_HPP

#include <Volcano/Details/Common.hpp>

#define VOLCANO_INLINE VOLCANO_DETAILS_INLINE

#define VOLCANO_API VOLCANO_DETAILS_API

#define VOLCANO_VERSION_MAJOR VOLCANO_DETAILS_VERSION_MAJOR
#define VOLCANO_VERSION_MINOR VOLCANO_DETAILS_VERSION_MINOR
#define VOLCANO_VERSION_PATCH VOLCANO_DETAILS_VERSION_PATCH

#ifdef VOLCANO_DETAILS_DEBUG
#   define VOLCANO_DEBUG
#endif

#define VOLCANO_BEGIN namespace Volcano {
#define VOLCANO_END }

#endif // VOLCANO_COMMON_HPP
