//
//
#ifndef VOLCANO_MODELCOMPILER_COMMON_H
#define VOLCANO_MODELCOMPILER_COMMON_H

#include <Volcano/Common.h>

#define VOLCANO_MODELCOMPILER_BEGIN VOLCANO_BEGIN namespace ModelCompiler {
#define VOLCANO_MODELCOMPILER_END } VOLCANO_END

#endif // VOLCANO_MODELCOMPILER_COMMON_H
