//
//
#ifndef VOLCANO_CLIENT_INPUT_COMMON_HPP
#define VOLCANO_CLIENT_INPUT_COMMON_HPP

#include <Volcano/Client/Common.hpp>

#define VOLCANO_CLIENT_INPUT_BEGIN VOLCANO_CLIENT_BEGIN namespace Input {
#define VOLCANO_CLIENT_INPUT_END } VOLCANO_CLIENT_END

#endif // VOLCANO_CLIENT_INPUT_COMMON_HPP
