//
//
#ifndef VOLCANO_PHYSICS_BULLET_COMMON_HPP
#define VOLCANO_PHYSICS_BULLET_COMMON_HPP

#include <Volcano/Physics/Common.hpp>

#define VOLCANO_PHYSICS_BULLET_BEGIN VOLCANO_PHYSICS_BEGIN namespace Bullet {
#define VOLCANO_PHYSICS_BULLET_END } VOLCANO_PHYSICS_END

#endif // VOLCANO_PHYSICS_BULLET_COMMON_HPP
