//
//
#ifndef VOLCANO_DRIVERS_INPUT_COMMON_HPP
#define VOLCANO_DRIVERS_INPUT_COMMON_HPP

#include <Volcano/Drivers/Common.hpp>

#define VOLCANO_DRIVERS_INPUT_BEGIN VOLCANO_DRIVERS_BEGIN namespace Input {
#define VOLCANO_DRIVERS_INPUT_END } VOLCANO_DRIVERS_END

#endif // VOLCANO_DRIVERS_INPUT_COMMON_HPP
